query mediaList($pageNumber: Int, $in: [Int]) {
  Page(perPage: 50, page: $pageNumber) {
    characters(sort: ID, id_in: $in) {
      id
      gender
      media(perPage: 50, sort: ID) {
        nodes {
          title {
            romaji
            english
          }
        }
      }
    }
  }
}
