query charactersRandom($id: Int) {
	Character(id: $id) {
		id
		siteUrl
		image {
			large
		}
		name {
			native
			alternative
			alternativeSpoiler
			userPreferred
			full
		}
		gender
		media(perPage: 1, sort: [FAVOURITES_DESC, POPULARITY_DESC]) {
			edges {
				node {
					isAdult
					title {
						romaji
					}
				}
			}
		}
	}
}
